[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "chmod -R 755 storage",
    "chmod -R 755 bootstrap/cache"
]

[phases.deploy]
cmds = [
    "sleep 10",
    "php artisan migrate --force || echo 'Migration failed'",
    "php artisan db:seed --force || echo 'Seeding failed'",
    "php artisan storage:link || echo 'Storage link failed'",
    "php artisan config:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
