[variables]
PHP_VERSION = "8.2"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan route:clear", 
    "php artisan view:clear",
    "php artisan migrate --force",
    "php artisan db:seed --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"